/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "design.v:17.1-48.10" *)
module dut(trit_in, trit_out);
  wire data_a;
  (* src = "design.v:22.10-22.13" *)
  wire sel;
  (* src = "design.v:18.23-18.30" *)
  input [1:0] trit_in;
  wire [1:0] trit_in;
  (* src = "design.v:19.23-19.31" *)
  output [1:0] trit_out;
  wire [1:0] trit_out;
  assign trit_out[0] = trit_in[0] & ~(trit_in[1]);
  assign data_a = trit_in[0];
  assign sel = trit_in[1];
  assign trit_out[1] = trit_in[1];
endmodule
