/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "design.v:12.1-26.10" *)
module dut(trit_in, trit_out);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "design.v:13.23-13.30" *)
  input [1:0] trit_in;
  wire [1:0] trit_in;
  (* src = "design.v:14.23-14.31" *)
  output [1:0] trit_out;
  wire [1:0] trit_out;
  assign _0_ = trit_in[0] & ~(trit_in[1]);
  assign _1_ = trit_in[0] & trit_in[1];
  assign trit_out[0] = _1_ | _0_;
  assign _2_ = trit_in[1] & ~(trit_in[0]);
  assign trit_out[1] = _1_ | _2_;
endmodule
