/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "design.v:6.1-21.10" *)
module dut(trit_in, trit_out);
  (* src = "design.v:7.23-7.30" *)
  input [1:0] trit_in;
  wire [1:0] trit_in;
  (* src = "design.v:8.23-8.31" *)
  output [1:0] trit_out;
  wire [1:0] trit_out;
  assign trit_out[0] = trit_in[0] & ~(trit_in[1]);
  assign trit_out[1] = ~(trit_in[0] | trit_in[1]);
endmodule
