#!/usr/bin/env python3
"""
build_report.py — Assembles the final simulation_log.md report.

Combines:
  - Simulation output
  - Hardware metrics (cell count, transistors, density)
  - Timing estimates
  - Embedded waveform and schematic images
"""

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path


def load_text(path: str, fallback: str = "_Not available._") -> str:
    p = Path(path)
    if p.exists() and p.stat().st_size > 0:
        return p.read_text().strip()
    return fallback


def load_json(path: str) -> dict:
    p = Path(path)
    if p.exists():
        try:
            return json.loads(p.read_text())
        except Exception:
            pass
    return {}


def build_metrics_table(metrics: dict) -> str:
    if not metrics:
        return "_Metrics not available._"

    summary = metrics.get("summary", {})
    breakdown = metrics.get("cell_breakdown", [])

    lines = []

    # ── Summary table ─────────────────────────────────────────
    lines += [
        "### Hardware Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Total Cells | **{summary.get('total_cells', 'N/A')}** |",
        f"| Estimated Transistors | **{summary.get('estimated_transistors', 'N/A'):,}** |",
        f"| Estimated Die Area | **{summary.get('estimated_area_um2', 'N/A')} µm²** |",
        f"| Reference Node | {summary.get('reference_node', 'N/A')} |",
        f"| Wire Count | {metrics.get('wire_count', 'N/A')} |",
        f"| Port Count | {metrics.get('port_count', 'N/A')} |",
        "",
        "> ⚠️ Area & transistor counts are **educational estimates** based on generic "
        "7nm CMOS assumptions. Actual values depend on the target PDK and P&R tool.",
        "",
    ]

    # ── Cell breakdown table ──────────────────────────────────
    if breakdown:
        lines += [
            "### Cell-Level Breakdown",
            "",
            "| Cell Type | Count | Transistors Each | Transistors Total |",
            "|-----------|------:|-----------------:|------------------:|",
        ]
        for row in breakdown:
            lines.append(
                f"| `{row['cell_type']}` "
                f"| {row['count']} "
                f"| {row['transistors_each']} "
                f"| {row['transistors_total']} |"
            )
        lines.append("")

    return "\n".join(lines)


def build_report(
    project: str,
    sim_output: str,
    compile_log: str,
    metrics: dict,
    timing_text: str,
    has_waveform: bool,
    has_schematic: bool,
) -> str:

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    metrics_section = build_metrics_table(metrics)

    waveform_section = (
        "### Signal Waveform\n\n"
        "![Simulation Waveform](waveform.png)\n"
        if has_waveform
        else "> ⚠️ Waveform export was skipped (no VCD file generated).\n"
    )

    schematic_section = (
        "### Gate-Level Schematic\n\n"
        "![Gate-Level Schematic](schematic.svg)\n\n"
        "> Generated by `netlistsvg` from Yosys JSON netlist.\n"
        if has_schematic
        else "> ⚠️ Schematic generation skipped (netlist not available).\n"
    )

    report = f"""# 📊 EDA Report: `{project}`

> **Generated:** {now}  
> **Toolchain:** Icarus Verilog · GTKWave · Yosys · Netlistsvg  
> **Pipeline:** GitHub Actions — HDL Ecosystem

---

## 1. Simulation Log

```text
{sim_output}
```

---

## 2. Compilation Output

```text
{compile_log}
```

---

## 3. Waveform Analysis

{waveform_section}

---

## 4. Gate-Level Synthesis

{schematic_section}

---

## 5. Hardware Metrics

{metrics_section}

---

## 6. Timing Analysis

```text
{timing_text}
```

---

## 7. Artifacts

| File | Description |
|------|-------------|
| `simulation_log.md` | This report |
| `waveform.png` | GTKWave timing diagram |
| `schematic.svg` | Gate-level schematic (netlistsvg) |
| `schematic_gates.svg` | Yosys `show` gate diagram |
| `timing_report.txt` | Timing analysis / critical path |
| `hardware_metrics.json` | Structured metrics (JSON) |
| `synth_netlist.v` | Post-synthesis Verilog netlist |

---

<sub>🤖 Auto-generated by the HDL Ecosystem Pipeline · Do not edit manually</sub>
"""
    return report


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--project",        required=True)
    parser.add_argument("--sim-output",     default="sim_output.txt")
    parser.add_argument("--compile-log",    default="compile_log.txt")
    parser.add_argument("--metrics",        default="hardware_metrics.json")
    parser.add_argument("--timing",         default="timing_report.txt")
    parser.add_argument("--has-waveform",   default="false")
    parser.add_argument("--has-schematic",  default="false")
    parser.add_argument("--output",         default="simulation_log.md")
    args = parser.parse_args()

    report = build_report(
        project      = args.project,
        sim_output   = load_text(args.sim_output),
        compile_log  = load_text(args.compile_log),
        metrics      = load_json(args.metrics),
        timing_text  = load_text(args.timing),
        has_waveform = args.has_waveform.lower() == "true",
        has_schematic= args.has_schematic.lower() == "true",
    )

    Path(args.output).write_text(report)
    print(f"✅ Report written to: {args.output}")


if __name__ == "__main__":
    main()
